Repository JuliaDynamics/DynamicalSystemsBase.jl, pull requests merged in 2018-03, with the labels that each got.

#39 Estimate Delay
  src/dataset.jl
  src/reconstruction.jl
  test/dataset_tests.jl
  test/reconstruction_tests.jl
Labels: enhancement, testing

#43 Added Cao's method
  src/dynamicalsystem/famous_systems.jl
  src/reconstruction.jl
  test/reconstruction_tests.jl
Labels: documentation, enhancement, testing, wanted feature

#42 Add `mutual_info` option to estimate delay
  src/reconstruction.jl
Labels: documentation, performance, testing
